# -- Project shortcuts --
alias woke='cd ~/Repositories/jack0son/woke-dapp'
alias woke-app='cd ~/Repositories/jack0son/woke-dapp/@woke/app'
alias contracts='cd ~/Repositories/jack0son/woke-dapp/@woke/contracts-src'
alias dotfiles='cd ~/Repositories/jack0son/dotfiles'

# Woke Network
alias wcli-dev='DEBUG=* NODE_ENV=development ETH_ENV=development npm run cli'
alias wcli-local='ETH_ENV=goerli_infura NODE_ENV=production npm run cli'
alias wcli='ETH_ENV=goerli_infura NODE_ENV=production npm run --prefix /home/jack/Repositories/jack0son/woke-dapp/@woke/cli cli'

# Instances
alias ssh:woke-services-1='gcloud compute ssh --project woke-network-services --zone us-west2-b woke-services-1'
alias ssh:woke-services-2='gcloud compute ssh --project woke-network-services --zone us-west2-b woke-services-2'
alias ssh:geth-goerli-1='gcloud compute ssh --project woke-network-services --zone us-west2-a geth-goerli-1'
alias ssh:geth-goerli-2='gcloud compute ssh --project woke-network-services --zone us-west2-a geth-goerli-2'
alias ssh:geth-goerli-3='gcloud compute ssh --project woke-network-services --zone us-west2-b geth-goerli-3'

# Geth
alias pull-geth='docker pull ethereum/client-go:latest'
alias goerli-start='docker rm $(docker ps -aq --filter name=goerli); docker run --name goerli -d -p 8545:8545 -p 30303:30303 -v ~/.ethereum:/root/.ethereum ethereum/client-go --goerli --rpc --rpcport 8545 --rpcaddr "0.0.0.0" --rpccorsdomain "*" --rpcapi personal,eth,net,web3b'
alias goerli-attach='docker run -it -v ~/.ethereum:/root/.ethereum ethereum/client-go attach ipc:///root/.ethereum/goerli/geth.ipc'

# Replace with fstab config
alias mnt:freenas='sudo mount -v -t cifs -o username=jackson,workgroup=WORKGROUP,ip=192.168.1.161 //freenas.local/windows-media ./freenas/windows-media'

# KDE Plasma
alias plasma-reboot='kquitapp5 plasmashell && kstart5 plasmashell'

# Alias management
alias valias='vim ~/.bash_aliases'
alias salias='source ~/.bash_aliases'
alias vash='vim ~/.bashrc'

# -- disk usage --
alias dummy='ncudu'
alias duh='du -h'

# Directory aliases
alias dt='cd ~/Desktop'
alias dl='cd ~/Downloads'
alias gosrc='cd ~/go/src/github.com/jack0son'
alias repos='cd ~/Repositories'
alias sandbox='cd ~/Repositories/sandbox'
alias github='cd ~/Repositories/github'
alias jack0son='cd ~/Repositories/jack0son'
alias xfce4-config='cd ~/.config/xfce4/xfconf/xfce-perchannel-xml'
# Jump back n directories at a time
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias ......='cd ../../../../../'

# Shell Tools
alias rm='rm -Iv'
alias tll='tree -L 1'
alias tl='tree -L 2'
alias lt='ls -l --sort=time'
alias lh='ls -ld ~/.[^.]*'
alias lst='lsd -lt'
alias copy='xclip -sel clip'
alias diff="colordiff"
alias grepc='grep --color=always'
alias grepn='grep -rn --exclude-dir={node_modules,build} --exclude={"*.json",".*.*.swp*"}'
alias sdn='sudo shutdown now'
alias bh='cat ~/.bash_history'
alias bhg='cat ~/.bash_history | grep'

# My shell tools
alias ll='lsd -l'
alias tmux='tmux -2'

# Python
alias python3='python3'
alias pip='pip3'

# Packages
alias upgrade='sudo apt update -y && sudo apt upgrade -y'

# Docker
alias dcls='docker container ls'
alias dcs='docker container stop'
alias dl='docker logs --follow'
alias docker-enter='docker-compose run --rm --service-ports app /bin/bash'
alias docker-enter-again='docker-compose run --rm app /bin/bash'
alias docker-clean-images='sudo docker rmi $(sudo docker images -a --filter=dangling=true -q)'
alias docker-clean-ps='sudo docker rm $(sudo docker ps --filter=status=exited --filter=status=created -q)'

# Rust
#alias rustc='rust.rustc'
#alias cargo='rust.cargo'

# Networking
alias lsof-netproc='lsof -Pan -i'
#alias lsofnet='lsof -Pan -p PID -i'
alias pg='ping google.com'
alias netman-restart='sudo systemctl restart NetworkManager'
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"

# Vim
alias lswp='ls .*.*.sw*'
alias rmswp='rm .*.*.sw*' 
if type nvim > /dev/null 2>&1; then
  alias vim='nvim'
fi

# Git 
alias gs='git status'
alias lastcommit='git log --name-status HEAD^..HEAD'
alias gls="git log --pretty=format:\"%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%cn]\" --decorate"
alias gll="git log --pretty=format:\"%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [%cn]\" --decorate --numstat"
alias glc='lastcommit'
alias gitbnr='git symbolic-ref -q HEAD'  # with ref
alias gitbn='git rev-parse --abbrev-ref HEAD'  
alias gittf='git ls-tree -r $(gitbn) --name-only'
alias gbranchbydate='git for-each-ref --sort=committerdate refs/heads/ --format="%(committerdate:short) %(refname)"'
alias gbbd='gbranchbydate'
alias gbranchbydater='git branch -r --sort=committerdate --format="%(committerdate:short) %(refname)"'
alias gbbdr='gbranchbydater'
alias trackallremote='git branch -r | grep -v "\->" | while read remote; do git branch --track "${remote#origin/}" "$remote"; done'

# Config
alias trackpoint="sudo ~/scripts/trackpoint_settings.sh && sudo ~/scripts/mmb_paste-disable.sh"
alias mmb="~/scripts/mmb_paste-disable.sh"
alias myApps="apt search '~i!~M'"

# Utils
alias truffle-local="./node_modules/.bin/truffle"
alias ganache-local="./node_modules/.bin/ganache-cli"
alias wpscan='sudo docker run -it --rm wpscanteam/wpscan'
alias fuck='sudo $(history -p \!\!)'


